# Generated by Django 5.2.1 on 2025-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='mapa_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
