# Generated by Django 5.2.1 on 2025-05-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0002_cervejaria_mapa_embed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cervejaria',
            old_name='cidade',
            new_name='bairro',
        ),
    ]
