# Generated by Django 5.2 on 2025-05-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0003_rename_cidade_cervejaria_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejaria',
            name='foto',
            field=models.ImageField(upload_to='cervejarias_fotos/'),
        ),
        migrations.AlterField(
            model_name='cervejaria',
            name='mapa_embed',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CervejariaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cervejarias/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='cervejarias.cervejaria')),
            ],
        ),
    ]
