# Generated by Django 5.2 on 2025-05-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0004_alter_cervejaria_foto_alter_cervejaria_mapa_embed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cervejariaimagem',
            name='legenda',
        ),
    ]
