# Generated by Django 5.2.1 on 2025-05-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0005_remove_cervejariaimagem_legenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cervejaria',
            name='foto',
        ),
        migrations.DeleteModel(
            name='CervejariaImagem',
        ),
    ]
