# Generated by Django 5.2.1 on 2025-05-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0006_remove_cervejaria_foto_delete_cervejariaimagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CervejariaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cervejarias/')),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='cervejarias.cervejaria')),
            ],
        ),
    ]
