# Generated by Django 5.2 on 2025-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0007_cervejariaimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='cidade',
            field=models.CharField(default='Recife', max_length=100),
        ),
        migrations.AddField(
            model_name='cervejaria',
            name='estado',
            field=models.CharField(default='PE', max_length=100),
        ),
        migrations.AddField(
            model_name='cervejaria',
            name='logradouro',
            field=models.CharField(default='nao encontrado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cervejaria',
            name='numero',
            field=models.IntegerField(default='000'),
            preserve_default=False,
        ),
    ]
