# Generated by Django 5.2 on 2025-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0008_cervejaria_cidade_cervejaria_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejaria',
            name='numero',
            field=models.CharField(),
        ),
    ]
