# Generated by Django 5.2 on 2025-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0009_alter_cervejaria_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cervejaria',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='cervejarias/'),
        ),
    ]
