# Generated by Django 5.2 on 2025-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0010_cervejaria_descricao_cervejaria_foto_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cervejaria',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='cervejaria',
            name='foto_principal',
            field=models.ImageField(blank=True, default='cervejarias/sem_foto.jpg', null=True, upload_to='cervejarias/'),
        ),
    ]
