# Generated by Django 5.2 on 2025-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0011_remove_cervejaria_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='descricao',
            field=models.TextField(blank=True, default='nada', null=True),
        ),
        migrations.AlterField(
            model_name='cervejaria',
            name='foto_principal',
            field=models.ImageField(upload_to='cervejarias/'),
        ),
    ]
