# Generated by Django 5.2 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0013_cervejaria_slug_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejaria',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cervejaria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
