# Generated by Django 5.2 on 2025-05-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0014_alter_cervejaria_numero_alter_cervejaria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cervejaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='cervejarias.cervejaria')),
            ],
        ),
    ]
