# Generated by Django 5.2 on 2025-06-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0015_localizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cervejarias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('site', 'Website'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('valor', models.CharField(max_length=255)),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='cervejarias.cervejaria')),
            ],
        ),
    ]
