# Generated by Django 5.2.1 on 2025-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0016_cervejaria_dono_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejaria',
            name='cep',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
