# Generated by Django 5.2.1 on 2025-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervejarias', '0017_cervejaria_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejaria',
            name='mapa_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
